### ISSUE TITLE
no room id found in the package source  not recoirding for some reason i restarted it afterwards it worked doe 

### ISSUE THREAD

**Issue by nmro97** [Coombaa/TTAutoRecord#18]
![nnn](https://github.com/Coombaa/TTAutoRecord/assets/149392722/36571581-a535-4602-8787-c469fc2c7915)

**Comment by Coombaa** [comment]
This is supposed to happen. By default only the HTML is loaded for to reduce CPU and bandwidth usage. If the Room ID is not found then it means the firewall has been triggered and it will automatically reload the page in full to pass the firewall challenge. After that it will carry on with just HTML.

You will see this every now and again but it will carry on as normal and still get the ID after a retry, there's no need to restart it.

**Comment by nmro97** [comment]
Ive waited but didnt get it,thats why. Maybe i just gotta wait some longer thanks
________________________________
