### ISSUE TITLE
so i waited 10 min for passing firewall challenge

### ISSUE THREAD

**Issue by nmro97** [Coombaa/TTAutoRecord#20]
hi so  i waited 10 min he just did the  passing firewall challenge but didnt download it

**Comment by nmro97** [comment]
so still have the issue cant pass the firewall challenge for over 25 min

**Comment by Coombaa** [comment]
try this file in modules instead, i have increased the timer

https://github.com/Coombaa/TTAutoRecord/blob/4.1.3/modules/get_stream_link.py

**Comment by nmro97** [comment]
hi so it just randomly stopped in the night and did not record anyhting  as i could see , it couldnt pass the firewall challenge

**Comment by nmro97** [comment]
still doing it and cant pass the firewall challenge needs to get restarted in order to work

**Comment by nmro97** [comment]
hey it stopped again and didnt continue for 10 hours
