### ISSUE TITLE
after the error it stops working 

### ISSUE THREAD

**Issue by nmro97** [Coombaa/TTAutoRecord#23]
![the error i get](https://github.com/Coombaa/TTAutoRecord/assets/149392722/0d9f8c43-4537-4e00-bc8e-bb0242be4a76)

**Comment by FabLeKebab** [comment]
I had the same problem, I just had to reinstall everything (I removed all the modules and reinstalled all the modules) but since then, I have another issue that is already open. The response may be late but it will surely help others who have had this problem.

**Comment by Coombaa** [comment]
I think i've fixed this now, just testing for a while longer. So far running 10 hours with no problems.

**Comment by nmro97** [comment]
any news

**Comment by FabLeKebab** [comment]
> any news

For ? It's fixed, the problem is solved

- Personally, I have no problem; everything works perfectly since the correction with the new files!

**Comment by nmro97** [comment]
> > any news
> 
> For ? It's fixed, the problem is solved
> 
> * Personally, I have no problem; everything works perfectly since the correction with the new files!

so it never stoped working for ya ufter the new files ?

**Comment by FabLeKebab** [comment]
> > > any news
> > 
> > For ? It's fixed, the problem is solved
> > 
> > * Personally, I have no problem; everything works perfectly since the correction with the new files!
> 
> so it never stoped working for ya ufter the new files ?

No, no errors, except sometimes (once or twice in about ten hours) it gives errors and I have to restart, then it resumes but it was already doing that before, it's not bothersome 🤷🏻‍♂️

It doesn't work at all for you? You should use the previous version if it doesn't work with the new files; they're probably in the process of deploying the update to your account 🤔

**Comment by nmro97** [comment]
> > > > any news
> > > 
> > > 
> > > For ? It's fixed, the problem is solved
> > > 
> > > * Personally, I have no problem; everything works perfectly since the correction with the new files!
> > 
> > 
> > so it never stoped working for ya ufter the new files ?
> 
> No, no errors, except sometimes (once or twice in about ten hours) it gives errors and I have to restart, then it resumes but it was already doing that before, it's not bothersome 🤷🏻‍♂️
> 
> It doesn't work at all for you? You should use the previous version if it doesn't work with the new files; they're probably in the process of deploying the update to your account 🤔
> 
> To clarify: _I have been using it every day since the new files, for more than 10 hours with peaks of 12/13 lives at the same time, and no errors._

YES THE PROBLEm is that overnight it just stops  that was my problem

**Comment by FabLeKebab** [comment]
> > > > > any news
> > > > 
> > > > 
> > > > For ? It's fixed, the problem is solved
> > > > 
> > > > * Personally, I have no problem; everything works perfectly since the correction with the new files!
> > > 
> > > 
> > > so it never stoped working for ya ufter the new files ?
> > 
> > No, no errors, except sometimes (once or twice in about ten hours) it gives errors and I have to restart, then it resumes but it was already doing that before, it's not bothersome 🤷🏻‍♂️
> > 
> > It doesn't work at all for you? You should use the previous version if it doesn't work with the new files; they're probably in the process of deploying the update to your account 🤔
> > 
> > To clarify: _I have been using it every day since the new files, for more than 10 hours with peaks of 12/13 lives at the same time, and no errors._
> 
> YES THE PROBLEm is that overnight it just stops  that was my problem 

Like me before, now I no longer have this problem, it's strange that it happens to you... The only error I sometimes have is this:

![image.png](https://github.com/Coombaa/TTAutoRecord/assets/109556581/91cb2fb4-6bc2-4e16-9889-58ebd34ac829)

But that doesn't matter, I restart and it's good, have you tried with the previous versions and the new files? It's a stupid question, but I'm surprised it doesn't work for you...

**Comment by nmro97** [comment]
> > > > > > any news
> > > > > 
> > > > > 
> > > > > For ? It's fixed, the problem is solved
> > > > > 
> > > > > * Personally, I have no problem; everything works perfectly since the correction with the new files!
> > > > 
> > > > 
> > > > so it never stoped working for ya ufter the new files ?
> > > 
> > > 
> > > No, no errors, except sometimes (once or twice in about ten hours) it gives errors and I have to restart, then it resumes but it was already doing that before, it's not bothersome 🤷🏻‍♂️
> > > It doesn't work at all for you? You should use the previous version if it doesn't work with the new files; they're probably in the process of deploying the update to your account 🤔
> > > To clarify: _I have been using it every day since the new files, for more than 10 hours with peaks of 12/13 lives at the same time, and no errors._
> > 
> > 
> > YES THE PROBLEm is that overnight it just stops  that was my problem
> 
> Like me before, now I no longer have this problem, it's strange that it happens to you... The only error I sometimes have is this:
> 
> ![image.png](https://private-user-images.githubusercontent.com/109556581/341994758-91cb2fb4-6bc2-4e16-9889-58ebd34ac829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODc5NjMsIm5iZiI6MTcxOTA4NzY2MywicGF0aCI6Ii8xMDk1NTY1ODEvMzQxOTk0NzU4LTkxY2IyZmI0LTZiYzItNGUxNi05ODg5LTU4ZWJkMzRhYzgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMlQyMDIxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTc4Y2U1NDc0OGVjN2Q1ZTgxYzhmYzRjMjIzZTU4MzQ0NTkxZWM1Y2VjYjhlNTBmZjNhNmRhM2Q5MGMyZmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C5SVVxKjBJKn2oz-DeEstuFN1KPQCwWByLI_XImYEHU)
> 
> But that doesn't matter, I restart and it's good, have you tried with the previous versions and the new files? It's a stupid question, but I'm surprised it doesn't work for you...

olli know what i mean , and i still use the old files  and it works, so didnt try the new ones, but as i said im using it on a different pc so i cant check all the  time if its working or not , it  just randomly stops needs to be restarted, than works fine again for couple hours

**Comment by Luly-bit** [comment]
> > > > des nouvelles
> > > 
> > > 
> > > Pour ?  C'est réglé, le problème est résolu 
> > > 
> > > * Personnellement, je n'ai aucun problème ;  tout fonctionne parfaitement depuis la correction avec les nouveaux fichiers !
> > 
> > 
> > donc ça n'a jamais cessé de fonctionner pour toi après les nouveaux fichiers ?
> 
> Non, pas d'erreur, sauf parfois (une ou deux fois en dix heures environ) ça donne des erreurs et je dois redémarrer, puis ça reprend mais il faisait déjà ça avant, ce n'est pas gênant 🤷🏻‍♂️
> 
> Ça ne marche pas du tout pour toi ? Vous devez utiliser la version précédente si elle ne fonctionne pas avec les nouveaux fichiers ; ils sont probablement en train de déployer la mise à jour sur votre compte 🤔
> 
> Pour préciser : _ je l'utilise tous les jours depuis les nouveaux fichiers, depuis plus de 10 heures avec des pics de 12/13 lives en même temps, et aucune erreur. _

I think you got the numbers wrong lol 
It's not the same thing

**Comment by FabLeKebab** [comment]
Oh damn, my bad! Actually I thought it was the problem with the files (that he couldn't find a live). My mistake! 😅

**Comment by Coombaa** [comment]
I am aware of the crashing, I'm working on it, it's just takes a long time testing it after each change waiting 10+ hours each time. 

The one I am working on in the new branch is considerably more stable now. It's still working when I wake up, but I want it to work 24/7.

**Comment by Luly-bit** [comment]
> > > > > > des nouvelles
> > > > > 
> > > > > 
> > > > > Pour ?  C'est réglé, le problème est résolu 
> > > > > 
> > > > > * Personnellement, je n'ai aucun problème ;  tout fonctionne parfaitement depuis la correction avec les nouveaux fichiers !
> > > > 
> > > > 
> > > > donc ça n'a jamais cessé de fonctionner pour toi après les nouveaux fichiers ?
> > > 
> > > 
> > > Non, pas d'erreur, sauf parfois (une ou deux fois en dix heures environ) ça donne des erreurs et je dois redémarrer, puis ça reprend mais il faisait déjà ça avant, ce n'est pas gênant 🤷🏻‍♂️ 
> > > Ça ne marche pas du tout pour toi ?  Vous devez utiliser la version précédente si elle ne fonctionne pas avec les nouveaux fichiers ;  ils sont probablement en train de déployer la mise à jour sur votre compte 🤔 
> > > Pour préciser : _ je l'utilise tous les jours depuis les nouveaux fichiers, depuis plus de 10 heures avec des pics de 12/13 lives en même temps, et aucune erreur. _
> > 
> > 
> > OUI LE PROBLÈME c'est que du jour au lendemain ça s'arrête, c'était mon problème
> 
> Comme moi avant, maintenant je n'ai plus ce problème, c'est étrange que ça vous arrive... La seule erreur que j'ai parfois est celle-ci :
> 
> ![image.png](https://private-user-images.githubusercontent.com/109556581/341994758-91cb2fb4-6bc2-4e16-9889-58ebd34ac829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTMxODUsIm5iZiI6MTcxOTE1Mjg4NSwicGF0aCI6Ii8xMDk1NTY1ODEvMzQxOTk0NzU4LTkxY2IyZmI0LTZiYzItNGUxNi05ODg5LTU4ZWJkMzRhYzgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNDI4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjRjMmJjZWU5ODc2YmQzNTZmNmQzZTE4ZWE1YmE4NjgxNzQ5ZjFiN2M3NTkwZjE1ODczOTMwMTgzMGUzOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8rbTWrd3i-Xd8LyeZuPuneyL_bX4zTMSziE_GfUXIIg)
> 
> Mais ce n'est pas grave, je redémarre et c'est bon, as-tu essayé avec les versions précédentes et les nouveaux fichiers ? C'est une question stupide, mais je suis surpris que cela ne fonctionne pas pour vous...

This happens to me too but yes it's not super serious even if yes it would be better if it worked 24/24 7/7

**Comment by Coombaa** [comment]
> > > > > > any news
> > > > > 
> > > > > 
> > > > > For ? It's fixed, the problem is solved
> > > > > 
> > > > > * Personally, I have no problem; everything works perfectly since the correction with the new files!
> > > > 
> > > > 
> > > > so it never stoped working for ya ufter the new files ?
> > > 
> > > 
> > > No, no errors, except sometimes (once or twice in about ten hours) it gives errors and I have to restart, then it resumes but it was already doing that before, it's not bothersome 🤷🏻‍♂️
> > > It doesn't work at all for you? You should use the previous version if it doesn't work with the new files; they're probably in the process of deploying the update to your account 🤔
> > > To clarify: _I have been using it every day since the new files, for more than 10 hours with peaks of 12/13 lives at the same time, and no errors._
> > 
> > 
> > YES THE PROBLEm is that overnight it just stops  that was my problem
> 
> Like me before, now I no longer have this problem, it's strange that it happens to you... The only error I sometimes have is this:
> 
> ![image.png](https://private-user-images.githubusercontent.com/109556581/341994758-91cb2fb4-6bc2-4e16-9889-58ebd34ac829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTU2NTgsIm5iZiI6MTcxOTE1NTM1OCwicGF0aCI6Ii8xMDk1NTY1ODEvMzQxOTk0NzU4LTkxY2IyZmI0LTZiYzItNGUxNi05ODg5LTU4ZWJkMzRhYzgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNTA5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTg0MmVkMTQxYzdhMmI1ODQ0Y2NmMTEzNWYxODY0ZjQ3ZjkyMzEyMDZjN2UyN2M4YzY4Y2Q2OTA4MzhmMzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZRmSrRXFEsugEGkilkejiydtqco272MO0zUhAgt0WXQ)
> 
> But that doesn't matter, I restart and it's good, have you tried with the previous versions and the new files? It's a stupid question, but I'm surprised it doesn't work for you...

what is your pc specs and internet speed? not seen this one but I'm on 10Gbps

**Comment by Luly-bit** [comment]
> > > > > > > des nouvelles
> > > > > > 
> > > > > > 
> > > > > > Pour ?  C'est réglé, le problème est résolu 
> > > > > > 
> > > > > > * Personnellement, je n'ai aucun problème ;  tout fonctionne parfaitement depuis la correction avec les nouveaux fichiers !
> > > > > 
> > > > > 
> > > > > donc ça n'a jamais cessé de fonctionner pour toi après les nouveaux fichiers ?
> > > > 
> > > > 
> > > > Non, pas d'erreur, sauf parfois (une ou deux fois en dix heures environ) ça donne des erreurs et je dois redémarrer, puis ça reprend mais il faisait déjà ça avant, ce n'est pas gênant 🤷🏻‍♂️ Ça ne marche pas du tout pour toi ?  Vous devez utiliser la version précédente si elle ne fonctionne pas avec les nouveaux fichiers ;  ils sont probablement en train de déployer la mise à jour sur votre compte 🤔 
> > > > Pour préciser : _ je l'utilise tous les jours depuis les nouveaux fichiers, depuis plus de 10 heures avec des pics de 12/13 lives en même temps, et aucune erreur. _
> > > 
> > > 
> > > OUI LE PROBLÈME c'est que du jour au lendemain ça s'arrête, c'était mon problème
> > 
> > 
> > Comme moi avant, maintenant je n'ai plus ce problème, c'est étrange que ça vous arrive... La seule erreur que j'ai parfois est celle-ci : 
> > ![image.png](https://private-user-images.githubusercontent.com/109556581/341994758-91cb2fb4-6bc2-4e16-9889-58ebd34ac829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTU2NTgsIm5iZiI6MTcxOTE1NTM1OCwicGF0aCI6Ii8xMDk1NTY1ODEvMzQxOTk0NzU4LTkxY2IyZmI0LTZiYzItNGUxNi05ODg5LTU4ZWJkMzRhYzgyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QxNTA5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTg0MmVkMTQxYzdhMmI1ODQ0Y2NmMTEzNWYxODY0ZjQ3ZjkyMzEyMDZjN2UyN2M4YzY4Y2Q2OTA4MzhmMzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZRmSrRXFEsugEGkilkejiydtqco272MO0zUhAgt0WXQ)
> > Mais ce n'est pas grave, je redémarre et c'est bon, as-tu essayé avec les versions précédentes et les nouveaux fichiers ?  C'est une question stupide, mais je suis surpris que cela ne fonctionne pas pour vous...
> 
> quelles sont les spécifications de ton PC et la vitesse d'Internet ? pas vu celui-ci mais je suis sur 10Gbps

![image](https://github.com/Coombaa/TTAutoRecord/assets/172504396/481b0e99-f149-48e9-a130-1d1680f3b2a0)
same as FabLeKebab it does this 1 or 2 times in a 12 hour session

**Comment by nmro97** [comment]
everything works fine for me after the liveupdate from olli , but it does not record any non eu streams pls help oll
