### ISSUE TITLE
No Active stream links found

### ISSUE THREAD

**Issue by samwinchester-1** [Coombaa/TTAutoRecord#24]
Program has been working amazing for me for past few months. Thank you for all the hard work.

Ive been having an issue for the past 3 days. No matter what I try, my main account cant find stream links anymore. Ive been using this account for months without any issues ever. And everything loads fine in browser and app with this account.

 I've tried :
-logging in and out + inputting fresh cookies
-pulling cookies from firefox, chrome
-tried on local pc, server
-fresh download of the program
-setting language to another language then back to english
-using another account. Instantly works with another account
-letting the account chill with 0 activity for a day in case it was rate limited
-letting it run on the no stream links found status.

It seems account related but I have no idea how to troubleshoot or what I can try to fix this. Any advice would be appreciated brother.

![Screenshot_20240427_115726_Microsoft Remote Desktop](https://github.com/Coombaa/TTAutoRecord/assets/57845700/af56dfd4-ca11-4b86-b434-ae5e0b153065)

**Comment by Coombaa** [comment]
Hi, did you change your log in method at all recently? What do you currently use?

**Comment by samwinchester-1** [comment]
Nope, I use username and password to log in

**Comment by samwinchester-1** [comment]
any suggestions :/ still getting same thing a week later

**Comment by samwinchester-1** [comment]
Hey again, i had started using a new account to get around this but the new account is now having this issue as well. Any idea what I can try to fix?

**Comment by leekuanyewsgp** [comment]
Having the same issue as you too

**Comment by nmro97** [comment]
guys u should use the one older version its working fine for me  as i wait for an update on the newer one

**Comment by Coombaa** [comment]
Guys I am in the process of moving house right now, once I have set up my office i will revisit this


Kind Regards,

Ollie








---- On Sat, 08 Jun 2024 13:35:41 +0100 nmro97 ***@***.***> wrote ---





guys u should use the one older version its working fine for me  as i wait for an update on the newer one

**Comment by FabLeKebab** [comment]
Same here, for two days. It impacts everyone I think. And good luck with your move!

**Comment by Luly-bit** [comment]
Exactly the same as you, nothing works overnight and it doesn't matter if I use another account, nothing happens

**Comment by Coombaa** [comment]
> I'll rephrase: I've been experiencing the same issue for the past two or three days. Everything works fine the night before, but the next day, I encounter the same errors as described here, and this continues to happen. I want to emphasize that I've tried everything. I even reset my computer and did a full reinstallation of Windows, reinstalling everything, but the error persists. Whether I use the latest version (4.1.2) or the previous version (4.1.0), and even with a different account, it still doesn't work.
> 
> Thank you for your work and your presence. Good luck with your move.
> 
> Best regards, Fabien

Did you create the account using Google sign in or another method? If not try one with Google

**Comment by FabLeKebab** [comment]
I log in with the classic identification method, using my email address and password. I just tried with a Google account and it gives me the same issue. I tried with the latest version available (4.1.2) and the previous version (4.1.0) using both methods (Google identification and classic identification)

**Comment by Luly-bit** [comment]
> I log in with the classic identification method, using my email address and password. I just tried with a Google account and it gives me the same issue. I tried with the latest version available (4.1.2) and the previous version (4.1.0) using both methods (Google identification and classic identification)

I did the same thing and it didn't work either the same error keeps occurring even now, it doesn't find any live streams even though there are some with two different versions. Have you managed to solve it since then? It's a shame because it's the best available at the moment :(

**Comment by FabLeKebab** [comment]
> > I log in with the classic identification method, using my email address and password. I just tried with a Google account and it gives me the same issue. I tried with the latest version available (4.1.2) and the previous version (4.1.0) using both methods (Google identification and classic identification)
> 
> I did the same thing and it didn't work either the same error keeps occurring even now, it doesn't find any live streams even though there are some with two different versions. Have you managed to solve it since then? It's a shame because it's the best available at the moment :(

Unfortunately nothing, I tried everything, really everything. I tried to use a VPN to see if it was a "banned" connection but no, I disabled Adguard, Windows Defender... With my 4G+ as an access point, with a 2.4 GHz connection either.

It probably doesn't come from us, we'll have to wait until the developer is available (hoping there's a solution) but I have no doubt that there is one, all we can do is **wait** ⏳

**Comment by nmro97** [comment]
guys idk which version u guys using im using the V4.0.2 alpha  and it works for me

**Comment by FabLeKebab** [comment]
> guys idk which version u guys using im using the V4.0.2 alpha  and it works for me

I had tried again with version 4.1.2 (it worked great before) but not anymore. Then I tried with version 4.1.0, and it also doesn't work. Did you switch to 4.0.2 Alpha because the later versions didn't work either ?

_In any case, I will try the 4.0.2 Alpha version tomorrow morning, hoping that it works. If it does, I will let you know_

**Comment by Coombaa** [comment]
Please could you try these 2 files on the latest one. Today it stopped working for me too and I saw they completely changed everything. I think they may have been slowly rolling it out.

https://github.com/Coombaa/TTAutoRecord/blob/4.1.3-livepageupdate/modules/get_stream_link.py

https://github.com/Coombaa/TTAutoRecord/blob/4.1.3-livepageupdate/modules/user_check.py

**Comment by FabLeKebab** [comment]
> Please could you try these 2 files on the latest one. Today it stopped working for me too and I saw they completely changed everything. I think they may have been slowly rolling it out.
> 
> https://github.com/Coombaa/TTAutoRecord/blob/4.1.3-livepageupdate/modules/get_stream_link.py
> 
> https://github.com/Coombaa/TTAutoRecord/blob/4.1.3-livepageupdate/modules/user_check.py

THANK YOU VERY MUCH! **IT WORKS!** 

In less than 10 seconds, the live streams started recording (by replacing the files from version 4.1.2 with the two new). That's probably why the script cut out from time to time _sometimes I had to restart it because it gave errors._

Sincerely, thank you for resolving the problem and for your responsiveness!

**Comment by nmro97** [comment]
the latest one without  the new files are working fine for me with the new ones it doesnt ,wierd !

**Comment by Luly-bit** [comment]
Also functional for me!! thank you Coombaa!!

**Comment by FabLeKebab** [comment]
> the latest one without  the new files are working fine for me with the new ones it doesnt ,wierd !

I advise you to re-download version 4.1.2 by replacing the "2" with "X" so that you know you will have the new files in that one. Then, when it stops working for you too, you can try again with version "4.1.X" while waiting for Coombaa to deploy a new version.

TikTok changed their "system" entirely; it hasn't reached you yet (maybe that's why it was working fine for you and not for us)

**Comment by Coombaa** [comment]
Yeah they seem to be rolling it out per account which is why it fixed it when you made new accounts

**Comment by carlossoors** [comment]
It was working fine with the new files but apparently tiktok changed again
