### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by kegman70** [Coombaa/TTAutoRecord#25]
Can someone please explain how to install this?

**Comment by FabLeKebab** [comment]
It's simple, you need to install what is required. To do this :

On Windows 11, for example, when you right-click in the installation folder, you have a tab 'Open in Terminal' (I'm French so I don't know if the translation is correct)

A Terminal opens, and from there you # type: ```pip install -r requirements.txt```

Everything will be installed from there. As for 'pip,' it is already present during the installation of Python, you need to check a box at the bottom before installation if necessary, and that's it.
