### ISSUE TITLE
Issue with TikTok LIVE Tab Requiring Repeated Logins

### ISSUE THREAD

**Issue by Luly-bit** [Coombaa/TTAutoRecord#35]
Hello everyone,

Is anyone else experiencing this issue with the TikTok website? When I log in, everything works fine, but as soon as I go to the "LIVE" tab, TikTok asks me to log in again. I've tried on another computer, on my phone, and with different accounts, but nothing works. Even after logging in again, I can't access my live streams, even though my profile shows that I am logged in.

In summary, as soon as I click on the "LIVE" tab, TikTok asks me to log in again. I've cleared all my caches, restarted my PC, and sent a report to TikTok. I'm posting this to see if anyone else is experiencing this issue.

_If the problem gets resolved, I will update this post to let everyone know. If there is no edit, it means the issue is still ongoing.
Thanks in advance to anyone who tries to help._

https://github.com/Coombaa/TTAutoRecord/assets/172504396/0c1f9993-285e-41b5-9394-0e1124c429a2
_Here is a video example, I made a post on r\tiktokhelp if they ever have any answers_

**Comment by Coombaa** [comment]
Yes they have just made an update, if you log in and click on a live so it shows the live list in the sidebar then get your cookies it should work. However you need to replace this file as they now load the page data dynamically. It will be a bit slower and more CPU usage unfortunately.

Ignore the firewall challenge message i will sort it later

https://github.com/Coombaa/TTAutoRecord/blob/4.1.3-livepageupdate/modules/get_stream_link.py

**Comment by FabLeKebab** [comment]
Hello, same here, exactly as described. We have to wait for an update from Ollie. In any case I tried to retrieve the cookies from a live feed but it tells me that there are none. _No live to be clearer, it must be an update again_

**Comment by nmro97** [comment]
i tried using an agent  switcher switched to ios,  to get the cookies but its not working

**Comment by Luly-bit** [comment]
![image](https://github.com/Coombaa/TTAutoRecord/assets/172504396/c9bbe08f-e159-4ad8-a940-cfa1e35ab7b4)
It feels like that to me personally, active/not active/active/not active

**Comment by FabLeKebab** [comment]
> ![image](https://github.com/Coombaa/TTAutoRecord/assets/172504396/c9bbe08f-e159-4ad8-a940-cfa1e35ab7b4)
> It feels like that to me personally, active/not active/active/not active and : 
> 
> **2024-07-02 12:02:45 - INFO - No room ID found in the page source.
> 2024-07-02 12:02:48 - INFO - No room ID found in the page source.
> 2024-07-02 12:02:48 - INFO - No room ID found for f*******_ after retry.**

Yes, me too but when I look in the "videos" folder the videos seem to be present and complete, so it's strange... Perhaps a false positive ?

**Comment by nmro97** [comment]
ollie said vefore just ignore the error message , the newest version works for me with no errors
