### ISSUE TITLE
Room ID not found 

### ISSUE THREAD

**Issue by sriwanich** [Coombaa/TTAutoRecord#37]
i used TTAutoRecord Version 4.1.3 update 6 hours ago later
![Screenshot 2024-07-02 143616](https://github.com/Coombaa/TTAutoRecord/assets/10558483/b9060b79-4737-4807-ba6f-a801c6f2dad8)

**Comment by sriwanich** [comment]
if downgrade to version 4.1.0 system normal
![Screenshot 2024-07-02 145840](https://github.com/Coombaa/TTAutoRecord/assets/10558483/b3eaed40-96d3-423c-a22e-1a2f13b6a810)

**Comment by nmro97** [comment]
tiktok fixed their issue , any version works now the newest version with the updates works aswell

**Comment by Coombaa** [comment]
They have reverted the change, use the get_stream_link.py from the main repo now
