### ISSUE TITLE
today it just bugged and stopped working somehow

### ISSUE THREAD

**Issue by nmro97** [Coombaa/TTAutoRecord#39]
so today after working for few  days straight it just bugged and stopped working

**Comment by urkoneta** [comment]
same here

**Comment by nmro97** [comment]
so i just had the issue with the passing firewall challange keep challenging nothing happenes

**Comment by FabLeKebab** [comment]
For the moment, I don't have any issues; they must be doing it by region. I live in France. Maybe they're testing outside of Europe and then rolling it out more widely. For example, the "EditThisCookie" extension was removed from the Google Store (for security reasons, the code wasn't the same as the one on GitHub)
