### ISSUE TITLE
Starting livestream extractor.... (does not record)

### ISSUE THREAD

**Issue by bootyislife** [Coombaa/TTAutoRecord#4]
This was working fine but when I know someone I follow was live it wouldn't work. I refollowed the person, had other people live at same time, reauth'd with new cookie and it will won't work. It just stays on "starting livestream extractor..." even with multiple people live.

Note: It states "Successfully authenticated! Starting monitor.." so it's not issue on my end of things.

**Comment by bootyislife** [comment]
After like 10+ minutes it error'd 
![image](https://github.com/O11iee/TTAutoRecord/assets/40509526/63284537-1fa2-4b2a-9a66-04157df1ff40)

**Comment by nmro97** [comment]
hi i have the same error but i get the error after like 30 min

**Comment by O11iee** [comment]
> After like 10+ minutes it error'd ![image](https://user-images.githubusercontent.com/40509526/279276316-63284537-1fa2-4b2a-9a66-04157df1ff40.png)

Hi, please try this version and let me know how you get on: [https://github.com/O11iee/TTAutoRecord/issues/url](url)

**Comment by bootyislife** [comment]
> > After like 10+ minutes it error'd ![image](https://user-images.githubusercontent.com/40509526/279276316-63284537-1fa2-4b2a-9a66-04157df1ff40.png)
> 
> Hi, please try this version and let me know how you get on: https://github.com/O11iee/TTAutoRecord/releases/tag/v4.0.0-alpha

Does not fix it for me, the bat nor the exe. It performs the same as before and no longer gets lives/downloads them.
