### ISSUE TITLE
No active stream links found - No room ID found for [X] after retry.

### ISSUE THREAD

**Issue by FabLeKebab** [Coombaa/TTAutoRecord#42]
Hello, here's what happened about twenty minutes ago, and I don't understand why. Here are the actions I took:

- I deleted the entire folder
- I did a clean reinstallation of the latest available version (the April version)
- I logged out and back in several times (taking the cookies each time, tested three times)
- I restarted the computer and repeated the same steps

Édit : _I just tried with another account (Google), and it doesn't work either._
Édit (2) : _I just performed a system restore from 36 hours ago (dated August 13, 2024, at 11:09 AM), and still, it doesn't work._

Since then, it displays this:

![Sans titre](https://github.com/user-attachments/assets/98667535-2cee-4818-8116-03079fc7b0cf)

It keeps doing this in a loop. If you have any solutions, or better yet, if someone could send me their clean files (after removing all personal data), I would really appreciate it. Thank you!

**Comment by jean75000** [comment]
Hello,

I am using version 4.1.3 and so far I don't have this problem:

![image](https://github.com/user-attachments/assets/555bea3c-32ce-42f8-a0e4-d52f634e64cf)

**Comment by FabLeKebab** [comment]
> Bonjour,
> 
> J'utilise la version 4.1.3 et pour l'instant je n'ai pas ce problème :
> 
> ![image](https://private-user-images.githubusercontent.com/168682836/358199082-555bea3c-32ce-42f8-a0e4-d52f634e64cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzMxNjIsIm5iZiI6MTcyMzczMjg2MiwicGF0aCI6Ii8xNjg2ODI4MzYvMzU4MTk5MDgyLTU1NWJlYTNjLTMyY2UtNDJmOC1hMGU0LWQ1MmY2MzRlNjRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNDQxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWQxZGY2MTIwZDU2YjYzOGU1NDMxY2Q5OTk4ZWU5Y2Q5MTEzYmE1NmUwMmRhODY1MzVhMjQxMmU1Yjg3Njc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Knj8YMIdvmhaai9XVxviaTTEptoF63_bWWPb6BrsR2o)
> 
> J'utilise la dernière version de Firefox 129 EN et j'ai mis à jour certains packages : ![image](https://private-user-images.githubusercontent.com/168682836/358200402-6f59d2d5-aac1-443c-a50f-00b1a31d6223.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzMxNjIsIm5iZiI6MTcyMzczMjg2MiwicGF0aCI6Ii8xNjg2ODI4MzYvMzU4MjAwNDAyLTZmNTlkMmQ1LWFhYzEtNDQzYy1hNTBmLTAwYjFhMzFkNjIyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxNDQxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTMwMmUxMWFmODg5NmRmNzFiZTVhMDc3NGI0MWZjZjJmNzJiNmI0M2RkMzE4OWQ2ZTA2YmJmOWFjOTQ2NGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aumazsd-FCSB05sOGHd2EWoZ011gPJFfoYtB2z5pSwk)

I have always used version 4.1.0. Where can I find version 4.1.3, please? In the top right corner, it still shows "4.1.0," so I am surprised that version 4.1.3 exists. The latest repository I checked only provides version 4.1.0 (the April version in the "main" branch). If you could point me to the correct repository, I would appreciate it. Thank you!

**Comment by FabLeKebab** [comment]
> here is the link to 4.1.3: https://github.com/Coombaa/TTAutoRecord/archive/refs/heads/main.zip


https://github.com/user-attachments/assets/29f249d8-423c-441c-a0fc-6f94ed644b70

It seems like I've tried it, but it closes as soon as I open it. I doubt the developer is still active, so I'm going to give up and find something else... Thanks anyway!

**Comment by Luly-bit** [comment]
> > here is the link to 4.1.3: https://github.com/Coombaa/TTAutoRecord/archive/refs/heads/main.zip
> 
> Enregistrement.2024-08-16.080045.mp4
> 
> It seems like I've tried it, but it closes as soon as I open it. I doubt the developer is still active, so I'm going to give up and find something else... Thanks anyway!

I have the same issue; it just closes immediately without doing anything, it just shuts down.  
@jean75000 could you send your zip file after removing cookies and personal info please ?

**Comment by nmro97** [comment]
did u guys install the requirements on the new one ?

**Comment by FabLeKebab** [comment]
I even created a specific environment for TTAutoRecord with Conda. The dependencies installed successfully, but it still doesn't work. I'm going to try again by deleting the environment and proceeding in the usual way, even though it will likely tell me that everything is already installed

**Comment by jean75000** [comment]
my files:https://we.tl/t-sQFXcpA8VI

**Comment by FabLeKebab** [comment]
> my files:https://we.tl/t-sQFXcpA8VI

On my end, it’s not working either. I’m going to reset the PC and reinstall everything cleanly tonight. It’ll take some time, but at least I’ll have a clear mind about it. Thanks a lot for your help, guys!

**Comment by FabLeKebab** [comment]
I just reset my PC and reinstalled everything, **and it works!** It was probably an issue with my modules. The latest version is now working, thanks again!
